baseurl = "https://bioinfo.mbu.cas.cz/"
languageCode = "en-us"
title = "Bioinformatics core facility"
theme = "ananke"
author = "Martin Modrák"
canonifyurls = true
languagecode = "en"
#googleAnalytics = "UA-113619876-1"
#disqusShortname = "martinmodrak"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$","\\.nb\\.html$"]

#disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

[params]
  sitename = "Bioinformatics core facility"


[permalinks]
    post = "/:year/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cas-bioinf"
    weight = 4
